{
  description = "Node.js development environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }: 
  let
    system = "x86_64-linux";  # or "aarch64-linux" if you're on ARM
    pkgs = nixpkgs.legacyPackages.${system};
    # Import the default.nix generated by node2nix
    nodeEnv = import ./default.nix { inherit pkgs; };
  in {
    # devShells.${system}.default = pkgs.mkShell {
    #   buildInputs = [
    #     pkgs.nodejs
    #   ];
    #   shellHook = ''
    #     echo "Node.js $(node --version) environment"
    #   '';
    # };
    devShells.${system}.default = nodeEnv.shell;

    # Optionally, define a package for your project if you need to build it
    packages.${system}.default = nodeEnv.package;
  };
}
